### ISSUE TITLE
.znap.source.find error: no such file or directory

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-snap#106]
### Discussed in https://github.com/marlonrichert/zsh-snap/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **wesmarcum** August 21, 2021</sup>
Hi Marlon - 

First, thanks for all of your work on znap!  I've enjoyed using it for the last 8 months.

I've had an issue on MacOS and FreeBSD 13 with one of the recent updates.  When I start my shell, my prompt fails to build with the following errors:
```
$(build_prompt)
$(build_prompt) znap restart
Validating dotfiles...
Validation failed with the following errors:
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/ohmyzsh/lib/git.zsh: no such file or directory
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/ohmyzsh/plugins/zoxide/zoxide.plugin.zsh: no such file or directory
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh: no such file or directory
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh: no such file or directory
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh: no such file or directory
.znap.source.find:zf_ln:19: /Users/<redacted>/.local/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh: no such file or directory
Restart aborted.
```
I've checked the plugin folders, and all of the referenced .zsh files exist.

znap configuration:
```
zstyle ':znap:*' plugins-dir "$HOME/.local/share/zsh/plugins"
source "$HOME/.local/share/zsh/zsh-snap/znap.zsh"

znap prompt ohmyzsh/ohmyzsh agnoster

znap source ohmyzsh/ohmyzsh \
  lib/{git,grep,history,key-bindings,theme-and-appearance} \
  plugins/ansible \
  plugins/colored-man-pages \
  plugins/docker-compose \
  plugins/git \
  plugins/tmux

znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-history-substring-search
```
If I checkout commit `c0ae8cf`, everything works fine.  The most recent commit on Debian 10/11 seems to work with the same configuration.</div>

**Comment by marlonrichert** [comment]
@wesmarcum I'm using macOS myself and I'm unable to reproduce this. Does this happen only with `znap restart` or also when you start a new terminal?

**Comment by GianlucaFicarelli** [comment]
Same problem here, after a new installation.
It happens opening a new terminal, or also running manually `znap source marlonrichert/zsh-autocomplete` or any other plugin.
The last working commit is `c0ae8cf1`, and it broke at `9111ebf`.
Mac OS 10.15.7, zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by wesmarcum** [comment]
Thanks for the quick response on this one.  The error occurs when opening a new terminal or running `znap restart`.  The strange thing is I don't get the error with the exact same config on Debian:

_Broken_:
macOS 11.5.2 / zsh 5.8
FreeBSD 13 / zsh 5.8

_Working_:
Debian 10 / zsh 5.7
Debian 11 / zsh 5.8

**Comment by marlonrichert** [comment]
I was able to reproduce it and it's fixed now. It turned out that `zf_ln`'s error message is rather misleading: Because of a stray `shift` statement, the second non-option argument to `zf_ln` was `''`.

> The strange thing is I don't get the error with the exact same config on Debian

The difference appears to be permissions: I wasn't able to reproduce the bug until I noticed you keep your plugins in `~/.local/share`. I then did `chmod 0700` on my own plugins dir and voilà: I got the same error message.

**Comment by wesmarcum** [comment]
I'm still having a similar issue.  :-(

With the latest commit, and my original `.zshrc` the prompt still fails and I see validation errors:
```
$(build_prompt)
$(build_prompt) znap restart
Validating dotfiles...
Validation failed with the following errors:
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/ohmyzsh/lib/git.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/ohmyzsh/plugins/zoxide/zoxide.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/.local/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh: no such file or directory
Restart aborted.
$(build_prompt)
```
I also tried to set permissions by using `chmod -R 0777 plugins/`, but that didn't seem to make a difference.

Next, I tested with your example `.zshrc` and reduced my `.zshrc` to the following:
```
# Download Znap, if it's not there yet.
[[ -f ~/Git/zsh-snap/znap.zsh ]] ||
    git clone https://github.com/marlonrichert/zsh-snap.git ~/Git/zsh-snap

source ~/Git/zsh-snap/znap.zsh  # Start Znap

# `znap prompt` reduces your shell's startup time to just 15-40 ms!
znap prompt sindresorhus/pure

# `znap source` automatically downloads and installs your plugins.
znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting

# `znap eval` caches any kind of command output for you.
znap eval iterm2 'curl -fsSL https://iterm2.com/shell_integration/zsh'
```
Note that ~/Git did not exist in my home dir.  I then started a fresh session, and the pure prompt builds, but I still get errors on the other plugins:
```
~
❯ znap restart
Validating dotfiles...
Validation failed with the following errors:
.znap.source.link:zf_ln:18: /Users/<redacted>/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/Git/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh: no such file or directory
.znap.source.link:zf_ln:18: /Users/<redacted>/Git/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh: no such file or directory
Restart aborted.
```
Permissions on ~/Git:
```
drwxr-xr-x    7 <redacted>  staff   224 Aug 22 11:23 Git
```
Sub-dirs:
```
drwxr-xr-x  19 <redacted>  staff  608 Aug 22 11:23 pure
drwxr-xr-x  17 <redacted>  staff  544 Aug 22 11:23 zsh-autocomplete
drwxr-xr-x  27 <redacted>  staff  864 Aug 22 11:23 zsh-autosuggestions
drwxr-xr-x  14 <redacted>  staff  448 Aug 22 11:23 zsh-snap
drwxr-xr-x  23 <redacted>  staff  736 Aug 22 11:23 zsh-syntax-highlighting
```

If I checkout commit [c0ae8cf](https://github.com/marlonrichert/zsh-snap/commit/c0ae8cf17d184314f6a833c1e4504cc9e6c00699), both configurations work without error.

**Comment by marlonrichert** [comment]
Thanks for the test case. That helped me reproduce it. Now it should really be fixed.
