### ISSUE TITLE
Hangs in "Username for github"

### ISSUE THREAD

**Issue by muuvmuuv** [marlonrichert/zsh-snap#152]
Trying to update my plugins rn, but it keeps me asking about my GH username and just hangs forever if I typed it in and pressed enter.

![Bildschirmfoto 2021-12-17 um 13 36 34](https://user-images.githubusercontent.com/11534760/146545721-21f58e53-bc35-49d1-9f25-ec0151934295.png)

And I just noticed that using `~` does not work for the HOME dir. You can see in the screenshot that it adds a `\`.

**Comment by marlonrichert** [comment]
Fixed. By the way: The install script is meant only for _adjusting your Znap installation._ To update your plugins, use `znap pull`.

**Comment by muuvmuuv** [comment]
@marlonrichert thanks :) yes, I just tried it that way because I thought my installation is malicious.

**Comment by muuvmuuv** [comment]
@marlonrichert it still hangs in the username prompt... any ideas?

**Comment by marlonrichert** [comment]
> nevermind it was `zdharma/fast-syntax-highlighting` which is now `zdharma-continuum/fast-syntax-highlighting`

OK, that’s a case that Znap is not prepared for. Thanks for figuring that out. I could add some code to handler that.

**Comment by marlonrichert** [comment]
@muuvmuuv I made an issue for it: #155 

Pull requests welcome, if you feel like helping out. 🙂
